Repository carlosricov/Personal-Portfolio, pull requests merged in 2021-11, with the labels that each got.

#23 011 education pg
  app/__init__.py
  app/static/css/education.css
  app/static/css/landing_style.css
  app/templates/base.html
  app/templates/education.html
  app/templates/index.html
  app/templates/portfolio.html
Labels: enhancement, Back end, Front end

#26 Tweaks education pg styling
  app/templates/education.html
Labels: bug

#27 update icon
  app/static/img/favicon.ico
  app/templates/base.html
Labels: Front end

#32 Updates education content
  app/static/css/education.css
  app/templates/education.html
Labels: Front end, More Content

#33 015 coursework
  app/static/css/coursework.css
  app/static/css/education.css
  app/static/css/landing_style.css
  app/static/css/portfolio.css
  app/static/img/cpe.svg
  app/static/img/ee.svg
  app/static/img/math.svg
  app/static/img/programming.svg
  app/templates/coursework.html
  app/templates/education.html
Labels: enhancement, Front end

#47 019 create project section
  app/__init__.py
  app/static/css/projects.css
  app/static/files/PercentError.pdf
  app/static/img/encrypta.png
  app/static/img/flaskblog.png
  app/static/img/ohm.png
  app/static/img/portfolio.png
  app/static/img/practicetyper.png
  app/static/img/python.png
  app/static/img/rlh.png
  app/static/img/skiplist.png
  app/static/img/tagbot.png
  app/templates/coursework.html
  app/templates/education.html
  app/templates/experience.html
  app/templates/portfolio.html
  app/templates/projects.html
  app/templates/skills.html
Labels: enhancement, Back end, Front end
